[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
edition = "2018"
name = "evaluator"
version = "0.1.0"

[dependencies]
random = "0.12.2"

[dependencies.tensorflow]
version = "0.10.0"
features = ["tensorflow_unstable"]
